version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  target-branch: development
  ignore:
  - dependency-name: mime
    versions:
    - 2.5.0
    - 2.5.2
  - dependency-name: ini
    versions:
    - 1.3.8
  - dependency-name: react-scripts
    versions:
    - 4.0.1
    - 4.0.2
    - 4.0.3
  - dependency-name: zencashjs
    versions:
    - 1.2.6
    - 1.2.7
  - dependency-name: react
    versions:
    - 16.14.0
  - dependency-name: react-qr-svg
    versions:
    - 2.3.0
  - dependency-name: lodash
    versions:
    - 4.17.20
    - 4.17.21
  - dependency-name: y18n
    versions:
    - 3.2.2
  - dependency-name: react-bootstrap
    versions:
    - 1.4.3
    - 1.5.0
    - 1.5.1
  - dependency-name: handlebars
    versions:
    - 4.7.6
    - 4.7.7
  - dependency-name: http-proxy
    versions:
    - 1.18.1
  - dependency-name: websocket-extensions
    versions:
    - 0.1.4
  - dependency-name: acorn
    versions:
    - 5.7.4
  - dependency-name: react-dom
    versions:
    - 16.13.0
  - dependency-name: eslint-utils
    versions:
    - 1.4.3
